name: GitHub Secrets

on:
  workflow_dispatch:
    
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Depoloying to production envt"
      - run: |
            echo "sec1: ${{ secrets.AZURE_CREDENTIALS  }}"
            echo "sec2: ${{ secrets.cder  }}"
